### ISSUE TITLE
Update go.mod file, canary Dockerfile to reflect Go 1.17

### ISSUE THREAD

**Issue by atc0005** [atc0005/send2teams#195]
## Summary

The Go 1.16 series is going EOL in ~ 2 months, so will need to update the Go version used for this project to reflect this.

## TODO

- [ ] Update README "requirements" to generically indicate "recent Go release" since this project doesn't (at present) have a fixed version requirement.
- [ ] Update `go.mod` file to reflect Go 1.17
- [ ] Update Dependabot (`dependabot.yml`) configuration to ignore Go versions greater than or less than 1.17.x
- [ ] Update "canary" Dockerfile to reflect Go 1.17.6, the latest in the 1.17.x series
- [ ] Run `go mod tidy && go mod vendor`
